version: 0.0
os: windows
files:
  - source: \index.html
    destination: c:\inetpub\wwwroot
    source: \src\HelloWorldWebCore\*
   
  
    destination: c:\inetpub\wwwroot\Great
hooks:
  BeforeInstall:
    - location: \before-install.bat
      timeout: 900
