version: 0.0
os: windows
files:
  - source: \
    destination: c:\inetpub\wwwroot
    
hooks:
  BeforeInstall:
    - location: \before-install.bat
      timeout: 900
      
  
   hooks:
ApplicationStart:
- location: \install.bat
timeout: 300
